<a href="https://colab.research.google.com/github/Preeti-san/Python-coding/blob/main/Task_sales.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

 To create a 2D array to represent sales data for 3 different products

In [41]:
import numpy as np
sales_data = np.array([
    [150, 120, 340, 860, 720,450], #product 1
    [650, 580, 220, 540, 300,700], #product 2
    [200, 250, 300, 350, 400,670]  #product 3
])

# Print the sales data.
print(sales_data)


[[150 120 340 860 720 450]
 [650 580 220 540 300 700]
 [200 250 300 350 400 670]]


In [42]:
# Reshape the array to separate the data into quarterly sales for each product.
quarterly_sales = np.reshape(sales_data, (-1))

# Print the reshaped array.
print(quarterly_sales)


[150 120 340 860 720 450 650 580 220 540 300 700 200 250 300 350 400 670]


In [43]:
print("Sales data:",sales_data,"\n")
x1=quarterly_sales[:-16]
print("Quarterly sales for prod1:",x1)
x2=quarterly_sales[6:-10]
print("Quarterly sales for prod2:",x2)
x3=quarterly_sales[12:-4]
print("Quarterly sales for prod3:",x3)

Sales data: [[150 120 340 860 720 450]
 [650 580 220 540 300 700]
 [200 250 300 350 400 670]] 

Quarterly sales for prod1: [150 120]
Quarterly sales for prod2: [650 580]
Quarterly sales for prod3: [200 250]


In [44]:
#To transpose the array
A=sales_data.T
print(A)

[[150 650 200]
 [120 580 250]
 [340 220 300]
 [860 540 350]
 [720 300 400]
 [450 700 670]]


In [45]:
sales_data1=sales_data[:3]
print(sales_data1)

[[150 120 340 860 720 450]
 [650 580 220 540 300 700]
 [200 250 300 350 400 670]]


In [46]:
#To calculate the total sales for each product
print("Product wise sales data:\n")
p1=sales_data1[0]
p2=sales_data1[1]
p3=sales_data1[2]
print("Sales for product1:",p1)
print("Sales for product2:",p2)
print("Sales for product3:",p3)
total_sales=np.sum(sales_data1,axis=1)
print("Total sales for each product:",total_sales)

Product wise sales data:

Sales for product1: [150 120 340 860 720 450]
Sales for product2: [650 580 220 540 300 700]
Sales for product3: [200 250 300 350 400 670]
Total sales for each product: [2640 2990 2170]


In [53]:
#TO calculate the total sales per quarter
print("Quaretrly sales for each product")
print(x1,x2,x3)
total_sales_per_quarter=np.sum(x1,axis=0),np.sum(x2,axis=0),np.sum(x3,axis=0)
print("Total sales per quarter:",total_sales_per_quarter)

Quaretrly sales for each product
[150 120] [650 580] [200 250]
Total sales per quarter: (270, 1230, 450)


In [54]:
#to add a new prod quarterly sales to the existing array
new_prod=np.array([470,690,360,280,390,580])

sales_data_new=np.vstack((sales_data1,new_prod))
print(sales_data_new)

[[150 120 340 860 720 450]
 [650 580 220 540 300 700]
 [200 250 300 350 400 670]
 [470 690 360 280 390 580]]


In [55]:
#TO SPLIT THE ARRAY INTO INDIVIDUAL SALES ARRAYS
split_array=np.vsplit(sales_data_new,4)
prod1=split_array[0]
prod2=split_array[1]
prod3=split_array[2]
prod4=split_array[3]
print("Sales for product1:",prod1,"\n")
print("sales for product2:",prod2,"\n")
print("Sales for product3:",prod3,"\n")
print("Sales for product4:",prod4)


Sales for product1: [[150 120 340 860 720 450]] 

sales for product2: [[650 580 220 540 300 700]] 

Sales for product3: [[200 250 300 350 400 670]] 

Sales for product4: [[470 690 360 280 390 580]]
